version: '3'
services:
  sjsons1:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - data:/data
  sjsons2:
    build: .
    ports:
     - "8082:8080"
    volumes:
     - data:/data
volumes:
  src:
  data: 